[package]
name = "kokomi-core"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
colored = "2.1.0"
rand = "0.8.5"
